# Generated by Django 3.1.1 on 2021-02-01 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=30, null=True)),
                ('date_and_time', models.DateTimeField(null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.doctor')),
                ('patient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.patient')),
            ],
        ),
    ]
